# Generated by Django 5.2.1 on 2025-06-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQueryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "query_text",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Текст запроса"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Завершен ли парсинг"
                    ),
                ),
                (
                    "total_results",
                    models.IntegerField(
                        default=0, verbose_name="Общее количество результатов"
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductResultModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.BigIntegerField(verbose_name="Внешний ID товара"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                (
                    "supplier",
                    models.CharField(max_length=255, verbose_name="Поставщик"),
                ),
                (
                    "supplier_rating",
                    models.FloatField(verbose_name="Рейтинг поставщика"),
                ),
                ("review_rating", models.FloatField(verbose_name="Рейтинг отзывов")),
                ("feedbacks", models.IntegerField(verbose_name="Количество отзывов")),
                ("price", models.BigIntegerField(verbose_name="Цена")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "search_query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="parser.searchquerymodel",
                    ),
                ),
            ],
            options={
                "db_table": "product_results",
                "ordering": ["id"],
            },
        ),
    ]
